<?php
	$eltLogin = $formAuth->get('login');
	$eltPassword = $formAuth->get('password');
	$formAuth->setAttribute('action', $this->url('auth', array('action'=>'index')));
	$this->headTitle($this->translate('Authentification'));
?>

<div class="modal-dialog">
	<div class="modal-content">
		<?php echo $this->form()->openTag($formAuth); ?>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Close') ?></span></button>
				<h4 class="modal-title"><?php echo $this->translate('Authentification') ?></h4>
				<?php 
					echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
			</div>
			<div class="modal-body">
				<p>
					<?php echo $this->formRow($eltLogin);
								echo '<br>'; 
								echo $this->formRow($eltPassword); ?>
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
				<button type="submit" class="btn btn-primary"><?php echo $this->translate('Ok') ?></button>
			</div>
			<?php echo $this->form()->closeTag(); ?>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->