<?php

  $title = $this->translate('Add Description');
  $this->headTitle($title);
  
  $request = $this->getHelperPluginManager()->getServiceLocator()->get('request');
  $router = $this->getHelperPluginManager()->getServiceLocator()->get('router');
  $matches = $router->match($request);
  
  if(is_null($matches)){
  	$route_name = 'album';
  	$params = array('lang'=>'en');
  } else {
  	$route_name = $matches->getMatchedRouteName();
  	$params = $matches->getParams();
  }
  
  if(isset($params['lang'])) $lang = $params['lang'];
  else $lang =  'en';
?>

<html lang="<?php echo $lang; ?>">

  <h1><?php echo $this->escapeHtml($title); ?></h1>

  <?php
 		$form = $this->form;
 		$form->setAttribute('action', $this->url('album', array(
         'action' => 'description',
         'title'  => $this->title,
    )));
 		$form->prepare();

 		echo $this->form()->openTag($form);
		echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('title'));
	echo $this->formHidden($form->get('artist'));
	echo $this->formRow($form->get('description'))." ";
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();