<?php

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td>
     	<a href="<?php echo $this->url('album',
             array('action'=>'infos', 'title' => str_replace ( ' ', '_', $album->title)));?>">
     		<?php echo $this->escapeHtml($album->title);?>
     	</a>
     </td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'title' => str_replace ( ' ', '_', $album->title)));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'title' => str_replace ( ' ', '_', $album->title)));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>