<?php

	$title = $this->escapeHtml($album->title)." by ".$this->escapeHtml($album->artist);
  $this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($album->title); ?> by <?php echo $this->escapeHtml($album->artist); ?></h1>
<br>
<h3>Description :</h3>
<?php echo $this->escapeHtml($album->description); ?>
<br><br>
<a href="<?php echo $this->url('album', array('action'=>'descriptionadd', 'id' => $album->id));?>">
	Add
</a>