<?php
	$request = $this->getHelperPluginManager()->getServiceLocator()->get('request');
	$router = $this->getHelperPluginManager()->getServiceLocator()->get('router');
	$matches = $router->match($request);
	
	if(is_null($matches)){
	    $route_name = 'album';
	    $params = array('lang'=>'en');
	} else {    
	    $route_name = $matches->getMatchedRouteName();
	    $params = $matches->getParams();
	}
	 
	if(isset($params['lang'])) $lang = $params['lang'];
	else $lang =  'en';
?>
<?php echo $this->doctype(); ?>
<html lang="<?php echo $lang; ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application', __NAMESPACE__))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application', __NAMESPACE__) ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home', __NAMESPACE__) ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('album', array('lang'=>$lang)) ?>"><?php echo $this->translate('Album', __NAMESPACE__) ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>
	                &copy; <?php echo $this->translate('All rights reserved.') ?> Quentin LECOURT
	                <a href="<?php $params['lang'] = 'fr'; echo $this->url($route_name,$params) ?>"><span class="flag flag-fr"><?php echo $this->translate('Fr', __NAMESPACE__) ?></span></a>
	                <a href="<?php $params['lang'] = 'en'; echo $this->url($route_name,$params) ?>"><span class="flag flag-en"><?php echo $this->translate('En', __NAMESPACE__) ?></span></a>
                </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
